apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeployment
metadata:
  name: gitops-depl
  namespace: jane
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps/
    path: guestbook

#  destination: {}

  type: automated

